envdir_home: "/etc/rf.d/env"

envdir_config:
  RF_DB_NAME: "{{ postgresql_database }}"
  RF_DB_USER: "{{ postgresql_username }}"
  RF_DB_PASSWORD: "{{ postgresql_password }}"
  RF_DB_HOST: "{{ postgresql_host }}"
  RF_DB_PORT: "{{ postgresql_port }}"
  AWS_PROFILE: "{{ aws_profile }}"
  AWS_DEFAULT_REGION: "{{ aws_region }}"
  RF_S3_BUCKET: "{{ s3_bucket }}"
  RF_SQS_QUEUE: "{{ sqs_queue }}"
  RF_SQS_DEAD_LETTER_QUEUE: "{{ sqs_dead_letter_queue }}"
  RF_WORKER_INSTANCES: "{{ worker_instances }}"
  RF_TEMP_DIR: "{{ temp_dir }}"

django_config:
  DJANGO_TEST_DB_NAME: "{{ django_test_database }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  DJANGO_STATIC_ROOT: "{{ django_static_root }}"
  DJANGO_MEDIA_ROOT: "{{ django_media_root }}"
  DJANGO_POSTGIS_VERSION: "{{ postgis_version }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"

postgis_version: 2.1.3
deploy_branch: "master"
django_secret_key: "{{ postgresql_password | md5 }}"

log_rotate_count: 5
log_rotate_interval: daily
